#-------------------------------
# Site Settings
title: sdemian.com
logo: # You can add own logo. For example '/images/logo.png'.
description: sdemian.com empowering business solutions
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Authors'
      url: '/authors/'
    - title: 'Videos'
      url: '/videos/'
    - title: 'About'
      url: '/about/'
    # - title: 'Pages'
    #   submenu:
    #   - url: '/about/'
    #     title: 'About'
    #   - url: '/contact/'
    #     title: 'Contact'
    #   - url: '/elements/'
    #     title: 'Elements'


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Thoughts, stories and ideas.
  hero__description: Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.
  hero__image: # You can add hero image. For example '/images/06.jpg'


#-------------------------------
# Author Global Settings
author:
  author__name: Sergii Demianchuk
  author__bio: Sergii Demianchuk is a Senior Software Engineering Technical Leader in the S&TO organization at Cisco, where he drives innovation in application security and vulnerability management. With 16 years of specialized experience in AppSec, Sergii has made significant contributions to SBOM security analysis and vulnerability management frameworks. He actively shapes industry standards as a member of both the OASIS OpenEoX Technical Committee and OASIS CSAF Technical Committee. His active participation in the CVE community reflects his commitment to advancing cybersecurity intelligence and standardization across the industry.
  author__avatar: /images/01-1.jpg


#-------------------------------
# Blog Section Settings
blog__settings:
  enable: true
  blog__title: Latest Posts
  blog__description:


#-------------------------------
# Videos Section Settings
videos__settings:
  enable: true
  videos__title: Latest Videos
  videos__description:


#-------------------------------
# Tag Section Settings
tag__settings:
  enable: true
  tag: ruby # To display the tag section, specify your favorite tag.


#-------------------------------
# Author Section Settings
author__section:
  enable: true
  author__section__title: Hello, my name is Sergii Demianchuk
  author__section__description: Sergii Demianchuk is a Senior Software Engineering Technical Leader in the S&TO organization at Cisco, where he drives innovation in application security and vulnerability management. With 16 years of specialized experience in AppSec, Sergii has made significant contributions to SBOM security analysis and vulnerability management frameworks. He actively shapes industry standards as a member of both the OASIS OpenEoX Technical Committee and OASIS CSAF Technical Committee. His active participation in the CVE community reflects his commitment to advancing cybersecurity intelligence and standardization across the industry.
  aurhor__section__button__text: More About Me
  aurhor__section__button__link: /about
  author__section__big__image: /images/sdemian-big-image.jpg
  author__section__small__image: /images/sdemian-small-image.jpg


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  enable: true
  mailchimp__title: Get interesting news
  mailchimp__description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp__identifier: sdemian.us15.list-manage.com/subscribe/post?u=eda65d04c2de1eabe1e1454fd&amp;id=f60d2b5c00&amp;f_id=00c7c2e1f0 # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp__input__text: Your email address
  mailchimp__button__text: Subscribe
  mailchimp__background__image: /images/subscribe-bg.jpg


#-------------------------------
# Footer Settings
footer__description: Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.


# Social Links
social:
- {icon: "fa-brands fa-x-twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-codepen", link: "https://codepen.io"}
- {icon: "fa-brands fa-pinterest", link: "https://pinterest.com"}
- {icon: "fa-brands fa-vimeo-v", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    # - title: 'Elements'
    #   url: '/elements/'


#-------------------------------
# Contact Settings
contact:
  email: xqadzekg # Add your form_id
  description: Contact me # Add a description of your form

# NOTE
# Mria theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: sdemian # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-EBL99TWX4F # Add your GA Tracking Id
